version: "3.6"
services:

  client:
    container_name: vvv_client
    restart: always
    build:
      context: ./client
    environment:
      - HOST=0.0.0.0
      - API_ENDPOINT
      - PREFIX
    ports:
      - 3000:3000

  server:
    container_name: vvv_server
    restart: always
    build:
      context: ./server
    environment:
      - NODE_ENV=production
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST=db
      - CORS
      - JWT_EXP_DAYS
      - JWT
      - PREFIX
    ports:
      - 4000:3000
    depends_on:
      - db

  db:
    container_name: vvv_db
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

  dbadmin:
    container_name: vvv_dbadmin
    restart: always
    image: sosedoff/pgweb
    ports:
      - "5000:8081"
    links:
      - db:db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - db
    logging:
      driver: "none"
